rwang5688/task_execution_pipeline_aws

.env
checkenv.sh
deploy.sh
remove.sh
resources/.gitignore
resources/jobs-list-apps-bucket.yml
resources/jobs-list-jobs-table.yml
resources/jobs-list-log-data-bucket.yml
resources/jobs-list-queues.yml
resources/jobs-list-source-data-bucket.yml
resources/package-lock.json
resources/package.json
resources/serverless.yml

add env and resources scripts

---

createJob/function.py
createJob/jobstable.py
createJob/serverless.yml

must remember table name has stage (e.g., dev, staging, prod) at the end!

table name must include stage (e.g., dev)

---

processJob/jobLog.py
processJob/processJob.py
processJob/xvsa.cpp

add the logic to upload logfile and send message to update job_status and logfile.

upload logfile and send update message

---

updateJob/.gitignore
updateJob/.vscode/settings.json
updateJob/event.json
updateJob/jobstable.py
updateJob/package-lock.json
updateJob/package.json
updateJob/requirements.txt
updateJob/s3util.py
updateJob/serverless.yml
updateJob/sqsutil.py
updateJob/updateJob.py

initial version of updateJob Lambda function

---

awsutil/s3util_test.py
awsutil/sqsutil_test.py

Remove unnecessary import sys statement.
Clean up awsutil tests and make sure they really work.

clean up awsutil tests

---

submitJob/submitJob.py

replace:
tool_name -> job_tool
source_name -> job_source

replace w job_tool and job_source

---

awsutil/sqsutil_test.py

check for received message is None.

add error checking in sqsutil_test.py

---

awsutil/submitJob.json
submitJob/submitJob.py
testfiles/submitJob.json

change submit message body to use job_tool and job_source as attributes.

submit action use job_tool and job_source

---

createJob/createJob.py
createJob/event.json
createJob/jobstable.py
resources/jobs-list-jobs-table.yml
submitJob/submitJob.py
testfiles/event.json

use attributes with job_prefix
- change event.json test file
- change dynamodb key schema definition to use job_id
- change *.py to use attributes with job_ prefix in messages and job record updates

use attributes with job_ prefix

---

createJob/createJob.py
createJob/jobstable.py
updateJob/jobstable.py
updateJob/updateJob.py

separate out parse_event_record so that event structure and jobs table structure are decoupled.

separate parse_event_record from create_job_record

---

createJob/serverless.yml
deploy.sh
processJob/processJob.py
processJob/xvsa.cpp
remove.sh
updateJob/event.json
updateJob/serverless.yml

update status + logfile; trigger log strm update

---

deploy.sh
remove.sh

Reorganize deploy and remove sequence.
Fully document manual workaround for extracting Cognito specific environment variables.

Reorganize deploy and remove sequence

---

processJob/processJob.py
processJob/s3util.py
processJob/sqsutil.py
processJob/xvsa.cpp

change from "python" to "python3".

get processjob container to work

---

.env
awsutil/s3util.py
awsutil/s3util_test.py
awsutil/sqsutil.py
awsutil/sqsutil_test.py
submitJob/s3util.py
submitJob/sqsutil.py
submitJob/submitJob.py
submitJob/submitJob.sh

s3util.py, sqsutil.py
Remove AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY from get_s3_client(), get_sqs_client().
Remove hard coding of region_name.
submitJob.py
Add get_env_vars() to get bucket_name, queue_name.
Remove hard coding of bucket_name, queue_name.
../.env
Add “export” in front of all assignments.
submitJob.sh
#!/bin/bash
. ../.env
. ../checkenv.sh
python3 ./submitJob.py $1 $2
Test
$ ./submitJob.sh xvsa source.tar.gz

pass in env vars to submitJob

---

createJob/createJob.py
createJob/s3util.py
createJob/sqsutil.py
updateJob/s3util.py
updateJob/sqsutil.py
updateJob/updateJob.py

s3util.py, sqsutil.py
Remove AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY from get_s3_client(), get_sqs_client().
Remove hard coding of region_name.
createJob.py
Remove #!/bin/bash.  This file does not need to be executable.
Deploy
$ . ../.env
$ . ../checkenv.sh
$ sls deploy
Test
From ../submitJob
$ ./submitJob.sh xvsa source.tar.gz
Check projectJob queue.

pass in env vars to createJob and updateJob

---

.env
processJob/env.sh
submitJob/env.sh

.env: reorganize env vars according to their domain.
env.sh: remove jobs-list frontend and api specific env var from workflow env scripts.

clean up env vars

---

.gitignore
processTask/.gitignore
processTask/Dockerfile
submitTask/.gitignore
submitTask/submitTask.sh

change from aws-admin_accessKeys.csv to aws-admin_credentials.csv.

use aws-admin_credentials.csv

---

processTask/.gitignore
processTask/.scan_log/scan.log
processTask/scan_result/scan_result.v
submitTask/submitTask.py
submitTask/task_config.json

Change submit task for real xvsa.
Add task_id to task config so that it shows up first.
Add mock .scan_log and scan_result to processTask for later use.

Change submit task for real xvsa

---

createTask/createTask.py
createTask/event.json
createTask/serverless.yml
createTask/tasktable.py

change createTask for real XVSA.
Note that dictionary assignment appears to be by reference.
This results in changes to the original task :(

change createTask for real XVSA

---

frontend/src/task-view.js
frontend/src/task.js
frontend/src/templates.js
task-list-service/handler.js

change frontend and task-list-service for real XVSA.
Add four columns and remove two columns.

change frontend, task-list-service for real XVSA

---

.env
createTask/serverless.yml
processTask/env.sh
resources/serverless.yml
resources/task-list-apps-bucket.yml
resources/task-list-log-data-bucket.yml
resources/task-list-preprocess-data-bucket.yml
resources/task-list-result-data-bucket.yml
submitTask/env.sh
task-list-service/serverless.yml
updateTask/serverless.yml
user-service/identity-pool.yml
user-service/serverless.yml

add TARGET_CLOUD and use in serverless.yml.

add TARGET_CLOUD and use in serverless.yml.

---

processTask/.dockerignore
submitTask/submitTask.sh

add comments to submitTask

---

processTask/.gitignore
processTask/.vscode/settings.json
submitTask/.gitignore
submitTask/.vscode/settings.json
submitTask/submitTask.sh

print real task config json file name.
.gitignore IDE artifacts.
remove .vscode directories.

print real task config json file name

---

createTask/.gitignore
createTask/.vscode/settings.json
processTask/.dockerignore
updateTask/.gitignore
updateTask/.vscode/settings.json

gitignore and dockerignore IDE artifacts in createTask, proocessTask, updateTask.

gitignore and dockerignore IDE artifacts

---

remove-task-list.sh
remove-task-workflow.sh
submitTask/submitTask.py

replace references to jobs to task-list or tasks

replace references to jobs to task-list or tasks

---

remove-task-pipeline.sh

forgot to remove the remove file table line

forgot to remove the remove file table line

---

createTask/event.json

fix createTask test data

---

processTask/taskResult.py

forgot to add user_id to S3 object

forgot to add user_id to S3 object

---

uploadTaskIssues/.gitignore
uploadTaskIssues/dotvfile.py
uploadTaskIssues/event.json
uploadTaskIssues/issuetable.py
uploadTaskIssues/package-lock.json
uploadTaskIssues/package.json
uploadTaskIssues/requirements.txt
uploadTaskIssues/s3util.py
uploadTaskIssues/serverless.yml
uploadTaskIssues/sqsutil.py
uploadTaskIssues/uploadTaskIssues.py

initial version of uploadTaskIssues include:
- uploadTaskIssues handler
- dot v file functions
- issue table functions

initial version of uploadTaskIssues

---

createTask/tasktable.py
processTask/bin/xvsa_start.sh
updateTask/tasktable.py
uploadTaskIssues/issuetable.py

create_task_record: use deep copy
get_task_record, get_issue_record: change return val from item to task_record, issue_record
bin/xvsa_start.sh: change from cp to mv so that mock issues are NOT duplicated

use deep copy in create_task_record; mv in mock

---

deploy-task-pipeline.sh
remove-task-pipeline.sh
uploadTaskIssues/.gitignore
uploadTaskIssues/csvfile.py
uploadTaskIssues/dotvfile.py
uploadTaskIssues/uploadTaskIssues.py
uploadTaskIssues/writeDotVFileIssuesCSV.py
uploadTaskIssues/xvsa-xfa-dummy.v

convert .v issues to task issues
write csv file to /tmp
upload csv file from /tmp to result data bucket
create writeDotVFileIssuesCSV.py to test dotvfile.py and csvfile.py.

uploadTaskIssues with CSV file

---

uploadTaskIssues/uploadTaskIssues.py

minor tweak to import statements

minor tweak to import statements

---

create_task/event.json
generate-task-summary/src/main/java/com/rwang5688/dal/Task.java
process_task/.dockerignore
process_task/.gitignore
submit_task/submit_task.py
submit_task/submit_task.sh
task-list-frontend/src/task-view.js
task-list-frontend/src/task.js
task-list-frontend/src/templates.js
task-list-service-v2/src/main/java/com/rwang5688/CreateTaskHandler.java
task-list-service-v2/src/main/java/com/rwang5688/UpdateTaskHandler.java
task-list-service-v2/src/main/java/com/rwang5688/dal/Task.java
update_task/event.json

1) change from task_config to task_context
2) change from task_source_fileinfo to task_fileinfo_json
3) change from task_source_code to task_source_code_zip
Note: task_preprocess_tar remains the same.

use task_fileinfo_json and task_source_code_zip

---

process_task/Dockerfile.xvsa

catch up to change on aws-cn repo.

change to default_credentials.csv

---

generate-task-summary/src/main/java/com/rwang5688/GenerateTaskSummaryHandler.java
process_task/.dockerignore
process_task/.gitignore
process_task/Dockerfile.xvsa
process_task/process_task.py
process_task/task_result.py
process_task/taskjson.py
process_task/taskjson_test.py

also: comment out PDF export in generate-task-summary.
This is to allows Lambda function to execute cleanly.
Otherwise, generate-task-summary queue will be stuck.

change scripts to write and read xcal-task.json

---

.env
create_task/create_task.py
create_task/serverless.yml
process_task/cachefile.py
process_task/env.sh
process_task_service/.gitignore
process_task_service/aws_ecr_push_process-task-cn.sh
process_task_service/aws_ecr_push_process-task.sh
process_task_service/package-lock.json
process_task_service/package.json
process_task_service/serverless.yml
resources/serverless.yml
resources/task-exec-queues.yml
submit_task/cachefile.py
submit_task/env.sh

Lambda + container function is in process_task_service.
Current assessment is the feature has some rough spots.
Ugly problem #1: Deployment depends on digest that comes after docker push. This means every time we push, we have to manually copy and paste the digest into serverless.yml.
Ugly problem #2: Lambda VM prevents container runtime from writing to working directory, possibly due to Lambda limitation of "must write to /tmp". Lambda should treat containers as stand alone without conventional Lambda restrcctions.

+process_task_trigger_queue, process_task_service

---

generate-task-summary/serverless.yml
process_task/process_task.py
update_task/update_task.py
upload_task_issues/dotvfile.py
upload_task_issues/serverless.yml

1) increase memory to 2048
- upload_task_issues, generate_task_summary
2) initialize result URLs to empty string
- upadate_task
3) add time measurements
- process_task

catch up to changes from week of 20210111

---

create_task/create_task.py
create_task/sqsutil.py
create_task/taskurl.py
process_task/sqsutil.py
submit_task/sqsutil.py
submit_task/submit_task.py
submit_task/submit_task.sh
update_task/sqsutil.py
upload_task_issues/sqsutil.py

1) fix typos in error messages (wrong function names)
2) remove unnecessary calls to sqs.list_queues()
3) make it optional to specify xcal-task.json file
4) make it optional to submit source_code.zip and generate source_code.zip URL

catch up to changes 2021-01-22

---

task-list-frontend/package-lock.json
task-list-frontend/package.json

upgrade immer to 8.0.1 per suggested fix for vulnerability.

upgrade immer dependencies to fix vulnerability

---

.env
process_task/env.sh
submit_task/env.sh

remove actual aws account id from repo

Remove actual aws account id from repo

---

.env
create_task/create_task.py
create_task/ecsutil.py
create_task/sqsutil.py
process_task/process_task.py
process_task/sqsutil.py
run_ecs_task.sh
submit_task/sqsutil.py
update_task/sqsutil.py
update_task/update_task.py
upload_task_issues/sqsutil.py

1) FORCE existence and execution of ECS cluster (but did not provide default names, ugh);
2) Enable SQS long polling by setting WaitTimeSeconds = 20.

force enable ECS cluster; enable SQS long polling
